namespace BattleBot_SimpleAI.BattleSolver
{
    public enum Element
    {
        GROUND, WALL, DEAD,
        CONSTRUCTION,
        CONSTRUCTION_DESTROYED_DOWN,
        CONSTRUCTION_DESTROYED_UP,
        CONSTRUCTION_DESTROYED_LEFT,
        CONSTRUCTION_DESTROYED_RIGHT,
        CONSTRUCTION_DESTROYED_DOWN_TWICE,
        CONSTRUCTION_DESTROYED_UP_TWICE,
        CONSTRUCTION_DESTROYED_LEFT_TWICE,
        CONSTRUCTION_DESTROYED_RIGHT_TWICE,
        CONSTRUCTION_DESTROYED_LEFT_RIGHT,
        CONSTRUCTION_DESTROYED_UP_DOWN,
        CONSTRUCTION_DESTROYED_UP_LEFT,
        CONSTRUCTION_DESTROYED_RIGHT_UP,
        CONSTRUCTION_DESTROYED_DOWN_LEFT,
        CONSTRUCTION_DESTROYED_DOWN_RIGHT,
        BULLET,
        TANK_UP,
        TANK_RIGHT,
        TANK_DOWN,
        TANK_LEFT,
        PLAYER_TANK_UP,
        PLAYER_TANK_RIGHT,
        PLAYER_TANK_DOWN,
        PLAYER_TANK_LEFT,
        OTHER_TANK_UP,
        OTHER_TANK_RIGHT,
        OTHER_TANK_DOWN,
        OTHER_TANK_LEFT
    }
}